services:
  postgres:
    image: postgres:16
    container_name: fynansee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: fynansee
    ports:
      - "5432:5432"
    volumes:
      - fynansee_db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fynansee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  fynansee_db:
